danmx/sigil

- cmd/sigil/main.go
- pkg/list/list.go
> Fixing multi-tag filtering in list

- Makefile
- cmd/sigil/main.go
Resolved issue https://github.com/danmx/sigil/issues/20
> Allow users to set custom log level

- cmd/sigil/main.go
- pkg/list/list.go
- pkg/session/session.go
Resolving issue https://github.com/danmx/sigil/issues/18
> Adding AWS config profile support

- Makefile
- pkg/session/session.go
- pkg/utils/ignore_signals.go
- pkg/utils/ignore_signals_windows.go
Copying approach from https://github.com/aws/aws-cli/blob/3175a42aaa287f2ae695d51096cc7efcbfc1d079/awscli/compat.py#L331
Addressing issue https://github.com/danmx/sigil/issues/39
> Ignore user input signals: SIGINT, SIGQUIT, SIGTSTP

- pkg/session/session.go
It should fix https://github.com/danmx/sigil/issues/46
> Matching execution pattern of session-manager-plugin with one in awscli

- README.md
That permissions are required for users not instance profiles
> Removing wrong dependency

- pkg/utils/utils.go
> filters out any non-running instances

- Makefile
@danmx could we release the most recent fixes?
Not sure what else is part of your release process other than updating the homebrew repo.
> bump version for release

- Makefile
- pkg/utils/ignore_signals.go
I often you ctrl+z to send the current process (like a text editor) to the background so I can work on other things.
> Catch SIGTSTP as well for CTRL+Z

- Makefile
- README.md
- docs/00-get-started.md
> update(version): to 0.4.0

- Makefile
- cmd/list.go
- pkg/aws/list.go
Fixing https://github.com/danmx/sigil/issues/61
> Fixing list filters

- README.md
- docs/usage/20-ssh.md
https://man.openbsd.org/ssh_config#TOKENS
> fix(ssh,doc): to use remote username ssh token

- pkg/aws/session.go
- pkg/aws/ssh.go
- pkg/ssh/ssh.go
Fixes issue https://github.com/danmx/sigil/issues/63
> fix(ssh,session): graceful failure on terminate session

- pkg/aws/session.go
> fix: app exit on failed session termination

- CHANGELOG.md
- tools/get_workspace_status.sh
> chore(release): 0.5.1

- .chglog/CHANGELOG.tpl.md
- .drone.yml
- CHANGELOG.md
> fix(drone): docker-release step

- .drone.yml
- CHANGELOG.md
> rm(drone): release notes

- CHANGELOG.md
- README.md
- docs/00-get-started.md
- tools/get_workspace_status.sh
> chore(release): version 0.6.0

- CHANGELOG.md
- docs/10-configuration.md
> fix(docs): adding profile config entry description

- CHANGELOG.md
- pkg/aws/ssh.go
> fix(aws): error log on a send ssh pub key failure

- CHANGELOG.md
- cmd/ssh.go
- docs/usage/20-ssh.md
> fix(cmd): clarify ssh usage

- .drone.yml
- CHANGELOG.md
> fix(drone): updating drone.yml signature

- CHANGELOG.md
- pkg/aws/BUILD.bazel
- pkg/aws/aws.go
- pkg/aws/aws_test.go
- pkg/aws/helpers/BUILD.bazel
- pkg/aws/helpers/helpers.go
- pkg/aws/list.go
- pkg/aws/list_test.go
- pkg/aws/log/log.go
- pkg/aws/session.go
- pkg/aws/session_test.go
- pkg/aws/ssh.go
- pkg/aws/ssh_test.go
> test(aws): adding unittests

- CHANGELOG.md
- WORKSPACE
> fix(bazel): semi-hermitizing Go SDK

- BUILD
- CHANGELOG.md
- WORKSPACE
- scripts/pre-commit.sh
> chore: refactoring dev tools

- CHANGELOG.md
- WORKSPACE
> chore(tools): updating dev tools

- CHANGELOG.md
- WORKSPACE
> chore(deps): updating AWS session-manager-plugin to version 1.2.7.0
